### ISSUE TITLE
Milestone 2 Objective

### ISSUE THREAD

**Issue by bigbulse** [ecrawford-0/Capstone#13]
This Milestone will focus on General Testing (now that hardware) and Defense Testing.

- [x] Flipper Zero Testing 
- [x] RFID Protection Sleeve 1 Testing
- [x] RFID Protection Sleeve 2 Testing
- [x] RFID Protection Wallet Testing
- [x] RFID Protection Purse Testing
- [x] NFC Protection Range Testing
- [x] Demo Video

**Comment by bigbulse** [comment]
RFID Defense Testing has been completed.

**Comment by bigbulse** [comment]
The Wave is Internet-based. Does not appear to actually use Radio Frequency.
