### ISSUE TITLE
Milestone Objectives

### ISSUE THREAD

**Issue by ecrawford-0** [ecrawford-0/Capstone#8]
Objectives to complete:
- [x] Research and Plan Capstone Project
- [x] Decide and Order Hardware
- [x] Create Backup Plan in event of Disaster
- [x] Perform Range Tests
